import { describe, it, expect } from 'vitest';
import { generatePythonScript, generateRScript, generateNpmScript } from '../utils/scriptExport.ts';
import type { ScriptExportParams } from '../utils/scriptExport.ts';

const baseParams: ScriptExportParams = {
  filename: 'my_data.tsv',
  fileType: 'binary',
  columnMapping: [1, 2, 3, 4],
  setNames: ['Vogelstein', 'COSMIC_CGC', 'OncoKB', 'IntOGen'],
  model: 'edwards-4',
  shapeColors: {
    A: '#FFF200', B: '#2E3192', C: '#ED1C24', D: '#808285',
    E: '#3C2415', F: '#9E1F63', G: '#CA4B9B', H: '#21AED1', I: '#F7941E',
  },
  enrichmentMetric: 'neglog10fdr',
  n: 4,
};

describe('generatePythonScript', () => {
  it('includes filename, model, column indices, set names, colors, metric and timestamp', () => {
    const script = generatePythonScript(baseParams);
    expect(script).toContain('# Generated by Venn Diagram Lab v');
    expect(script).toContain('my_data.tsv');
    expect(script).toContain('edwards-4');
    expect(script).toContain('[1, 2, 3, 4]');
    expect(script).toContain('Vogelstein');
    expect(script).toContain('COSMIC_CGC');
    expect(script).toContain('#FFF200');
    expect(script).toContain('#2E3192');
    expect(script).toContain('neglog10fdr');
    expect(script).toContain('analyze(ds, model="edwards-4")');
    expect(script).toContain('render_venn_svg');
    expect(script).toContain('render_upset');
    expect(script).toContain('render_network');
  });

  it('uses binary loading code for binary files', () => {
    const script = generatePythonScript(baseParams);
    expect(script).toContain('val in {"1", "true", "yes"}');
    expect(script).not.toContain('ITEM_DELIMITER');
  });

  it('uses aggregated loading code for aggregated files', () => {
    const script = generatePythonScript({ ...baseParams, fileType: 'aggregated', delimiter: ',' });
    expect(script).toContain('ITEM_DELIMITER = ","');
    expect(script).toContain('for item in cell.split(ITEM_DELIMITER)');
  });

  it('maps proportional model to model="proportional" and adds a note', () => {
    const script = generatePythonScript({ ...baseParams, model: '__proportional__' });
    expect(script).toContain('model="proportional"');
    expect(script).toContain('area-proportional');
  });

  it('uses pandas for xlsx files', () => {
    const script = generatePythonScript({ ...baseParams, filename: 'my_data.xlsx' });
    expect(script).toContain('pd.read_excel');
    expect(script).toContain('openpyxl');
  });
});

describe('generateRScript', () => {
  it('includes filename, model, 1-based column indices, set names, colors, metric and timestamp', () => {
    const script = generateRScript(baseParams);
    expect(script).toContain('# Generated by Venn Diagram Lab v');
    expect(script).toContain('my_data.tsv');
    expect(script).toContain('edwards-4');
    expect(script).toContain('COLUMNS <- c(2, 3, 4, 5)');
    expect(script).toContain('Vogelstein');
    expect(script).toContain('COSMIC_CGC');
    expect(script).toContain('#FFF200');
    expect(script).toContain('#2E3192');
    expect(script).toContain('neglog10fdr');
    expect(script).toContain('analyze(ds, model = "edwards-4")');
    expect(script).toContain('render_venn_svg');
    expect(script).toContain('render_upset');
    expect(script).toContain('render_network');
  });

  it('uses binary loading code for binary files', () => {
    const script = generateRScript(baseParams);
    expect(script).toContain('tolower(val) %in% c("1", "true", "yes")');
    expect(script).not.toContain('ITEM_DELIMITER');
  });

  it('uses aggregated loading code for aggregated files', () => {
    const script = generateRScript({ ...baseParams, fileType: 'aggregated', delimiter: ',' });
    expect(script).toContain('ITEM_DELIMITER <- ","');
    expect(script).toContain('strsplit(cell, ITEM_DELIMITER, fixed = TRUE)');
  });

  it('maps proportional model to model = "proportional" and adds a note', () => {
    const script = generateRScript({ ...baseParams, model: '__proportional__' });
    expect(script).toContain('model = "proportional"');
    expect(script).toContain('area-proportional');
  });

  it('uses openxlsx for xlsx files', () => {
    const script = generateRScript({ ...baseParams, filename: 'my_data.xlsx' });
    expect(script).toContain('openxlsx::read.xlsx');
  });
});

describe('generateNpmScript', () => {
  it('includes filename, model, column indices, set names, colors, metric and timestamp', () => {
    const script = generateNpmScript(baseParams);
    expect(script).toContain('// Generated by Venn Diagram Lab v');
    expect(script).toContain('my_data.tsv');
    expect(script).toContain('edwards-4');
    expect(script).toContain('[1, 2, 3, 4]');
    expect(script).toContain('Vogelstein');
    expect(script).toContain('COSMIC_CGC');
    expect(script).toContain('#FFF200');
    expect(script).toContain('#2E3192');
    expect(script).toContain('neglog10fdr');
    expect(script).toContain('import');
    expect(script).toContain('from \'venn-diagram-lab\'');
    expect(script).toContain('analyzeCsv(csv)');
    expect(script).toContain('toVennSvg(result, MODEL)');
    expect(script).toContain('toUpsetSvg(result)');
    expect(script).toContain('toNetworkSvg(result, \'jaccard\')');
    expect(script).toContain('toStatisticsTsv(result)');
  });

  it('uses binary loading code for binary files', () => {
    const script = generateNpmScript(baseParams);
    expect(script).toContain('Binary mode');
    expect(script).toContain('row[0]');
    expect(script).not.toContain('ITEM_DELIMITER');
  });

  it('uses aggregated loading code for aggregated files', () => {
    const script = generateNpmScript({ ...baseParams, fileType: 'aggregated', delimiter: ',' });
    expect(script).toContain('Aggregated mode');
    expect(script).toContain('const ITEM_DELIMITER = ","');
    expect(script).toContain('cell.split(ITEM_DELIMITER)');
  });

  it('maps proportional model to MODEL === "proportional" and adds a note', () => {
    const script = generateNpmScript({ ...baseParams, model: '__proportional__' });
    expect(script).toContain('MODEL = "proportional"');
    expect(script).toContain('area-proportional');
    expect(script).toContain('toProportionalSvg(result)');
  });

  it('adds Excel conversion comment for xlsx files', () => {
    const script = generateNpmScript({ ...baseParams, filename: 'my_data.xlsx' });
    expect(script).toContain('Excel file: convert to CSV first');
    expect(script).toContain('xlsx.readFile');
  });
});
