import { describe, it, expect } from 'vitest';
import { generatePythonScript, generateRScript, generateNpmScript } from '../utils/scriptExport.ts';
import type { ScriptExportParams } from '../utils/scriptExport.ts';

const baseParams: ScriptExportParams = {
  filename: 'my_data.tsv',
  fileType: 'binary',
  columnMapping: [1, 2, 3, 4],
  setNames: ['Vogelstein', 'COSMIC_CGC', 'OncoKB', 'IntOGen'],
  model: 'edwards-4',
  shapeColors: {
    A: '#FFF200', B: '#2E3192', C: '#ED1C24', D: '#808285',
    E: '#3C2415', F: '#9E1F63', G: '#CA4B9B', H: '#21AED1', I: '#F7941E',
  },
  enrichmentMetric: 'neglog10fdr',
  n: 4,
  sourceKind: 'file',
  hasHeader: true,
  sheetIndex: 0,
  headers: ['ID', 'Vogelstein', 'COSMIC_CGC', 'OncoKB', 'IntOGen'],
  rawData: [
    ['g1', '1', '1', '0', '0'],
    ['g2', '1', '0', '1', '0'],
  ],
};

describe('generatePythonScript', () => {
  it('includes filename, model, column indices, set names, colors, metric and timestamp', () => {
    const script = generatePythonScript(baseParams);
    expect(script).toContain('# Generated by Venn Diagram Lab v');
    expect(script).toContain('my_data.tsv');
    expect(script).toContain('edwards-4');
    expect(script).toContain('[1, 2, 3, 4]');
    expect(script).toContain('Vogelstein');
    expect(script).toContain('COSMIC_CGC');
    expect(script).toContain('#FFF200');
    expect(script).toContain('#2E3192');
    expect(script).toContain('neglog10fdr');
    expect(script).toContain('analyze(ds, model="edwards-4")');
    expect(script).toContain('render_venn_svg');
    expect(script).toContain('render_upset');
    expect(script).toContain('render_network');
  });

  it('uses binary loading code for binary files', () => {
    const script = generatePythonScript(baseParams);
    expect(script).toContain('val in {"1", "true", "yes"}');
    expect(script).not.toContain('ITEM_DELIMITER');
  });

  it('uses aggregated loading code for aggregated files', () => {
    const script = generatePythonScript({ ...baseParams, fileType: 'aggregated', delimiter: ',' });
    expect(script).toContain('ITEM_DELIMITER = ","');
    expect(script).toContain('for item in cell.split(ITEM_DELIMITER)');
  });

  it('maps proportional model to model="proportional" and adds a note', () => {
    const script = generatePythonScript({ ...baseParams, model: '__proportional__' });
    expect(script).toContain('model="proportional"');
    expect(script).toContain('area-proportional');
  });

  it('uses pandas for xlsx files', () => {
    const script = generatePythonScript({ ...baseParams, filename: 'my_data.xlsx' });
    expect(script).toContain('pd.read_excel');
    expect(script).toContain('openpyxl');
  });
});

describe('generateRScript', () => {
  it('includes filename, model, 1-based column indices, set names, colors, metric and timestamp', () => {
    const script = generateRScript(baseParams);
    expect(script).toContain('# Generated by Venn Diagram Lab v');
    expect(script).toContain('my_data.tsv');
    expect(script).toContain('edwards-4');
    expect(script).toContain('COLUMNS <- c(2, 3, 4, 5)');
    expect(script).toContain('Vogelstein');
    expect(script).toContain('COSMIC_CGC');
    expect(script).toContain('#FFF200');
    expect(script).toContain('#2E3192');
    expect(script).toContain('neglog10fdr');
    expect(script).toContain('analyze(ds, model = "edwards-4")');
    expect(script).toContain('render_venn_svg');
    expect(script).toContain('render_upset');
    expect(script).toContain('render_network');
  });

  it('uses binary loading code for binary files', () => {
    const script = generateRScript(baseParams);
    expect(script).toContain('tolower(val) %in% c("1", "true", "yes")');
    expect(script).not.toContain('ITEM_DELIMITER');
  });

  it('uses aggregated loading code for aggregated files', () => {
    const script = generateRScript({ ...baseParams, fileType: 'aggregated', delimiter: ',' });
    expect(script).toContain('ITEM_DELIMITER <- ","');
    expect(script).toContain('strsplit(cell, ITEM_DELIMITER, fixed = TRUE)');
  });

  it('maps proportional model to model = "proportional" and adds a note', () => {
    const script = generateRScript({ ...baseParams, model: '__proportional__' });
    expect(script).toContain('model = "proportional"');
    expect(script).toContain('area-proportional');
  });

  it('uses openxlsx for xlsx files', () => {
    const script = generateRScript({ ...baseParams, filename: 'my_data.xlsx' });
    expect(script).toContain('openxlsx::read.xlsx');
  });
});

describe('generateNpmScript', () => {
  it('includes filename, model, column indices, set names, colors, metric and timestamp', () => {
    const script = generateNpmScript(baseParams);
    expect(script).toContain('// Generated by Venn Diagram Lab v');
    expect(script).toContain('my_data.tsv');
    expect(script).toContain('edwards-4');
    expect(script).toContain('[1, 2, 3, 4]');
    expect(script).toContain('Vogelstein');
    expect(script).toContain('COSMIC_CGC');
    expect(script).toContain('#FFF200');
    expect(script).toContain('#2E3192');
    expect(script).toContain('neglog10fdr');
    expect(script).toContain('import');
    expect(script).toContain('from \'venn-diagram-lab\'');
    expect(script).toContain('analyzeCsv(csv)');
    expect(script).toContain('toVennSvg(result, MODEL)');
    expect(script).toContain('toUpsetSvg(result)');
    expect(script).toContain('toNetworkSvg(result, \'jaccard\')');
    expect(script).toContain('toStatisticsTsv(result)');
  });

  it('uses binary loading code for binary files', () => {
    const script = generateNpmScript(baseParams);
    expect(script).toContain('Binary mode');
    expect(script).toContain('row[0]');
    expect(script).not.toContain('ITEM_DELIMITER');
  });

  it('uses aggregated loading code for aggregated files', () => {
    const script = generateNpmScript({ ...baseParams, fileType: 'aggregated', delimiter: ',' });
    expect(script).toContain('Aggregated mode');
    expect(script).toContain('const ITEM_DELIMITER = ","');
    expect(script).toContain('cell.split(ITEM_DELIMITER)');
  });

  it('maps proportional model to MODEL === "proportional" and adds a note', () => {
    const script = generateNpmScript({ ...baseParams, model: '__proportional__' });
    expect(script).toContain('MODEL = "proportional"');
    expect(script).toContain('area-proportional');
    expect(script).toContain('toProportionalSvg(result)');
  });

  it('adds Excel conversion comment for xlsx files', () => {
    const script = generateNpmScript({ ...baseParams, filename: 'my_data.xlsx' });
    expect(script).toContain('Excel file: convert to CSV first');
    expect(script).toContain('xlsx.readFile');
  });
});

// Task 1: plumbing only. ScriptExportParams gains sourceKind/hasHeader/sheetIndex/headers/rawData
// so Task 2's generators can act on import provenance. The generators themselves do not yet use
// these fields — that behavior (inline embedding for paste/url, skipping open(FILE), etc.) is
// implemented in Task 2 and tested there.
describe('ScriptExportParams provenance plumbing', () => {
  const pasteParams: ScriptExportParams = {
    filename: 'pasted-data', fileType: 'aggregated', delimiter: ',',
    columnMapping: [0, 1], setNames: ['A', 'B'], model: 'venn2',
    shapeColors: { A: '#FFF200', B: '#2E3192' }, enrichmentMetric: 'neglog10fdr',
    n: 2, sourceKind: 'paste', hasHeader: true, sheetIndex: 0,
    headers: ['A', 'B'], rawData: [['g1;g2', 'g2;g3']],
  };

  it('accepts sourceKind, hasHeader, sheetIndex, headers and rawData', () => {
    expect(pasteParams.sourceKind).toBe('paste');
    expect(pasteParams.hasHeader).toBe(true);
    expect(pasteParams.sheetIndex).toBe(0);
    expect(pasteParams.headers).toEqual(['A', 'B']);
    expect(pasteParams.rawData).toEqual([['g1;g2', 'g2;g3']]);
  });

  it('generator behavior for sourceKind: "file" is unchanged (still opens FILE) — Task 2 implements the divergence', () => {
    const script = generatePythonScript(baseParams); // baseParams.sourceKind === 'file'
    expect(script).toContain('open(FILE');
  });
});

// Task 2: generators use import provenance to reproduce the app for every import path.
describe('Task 2: import-path parity', () => {
  const base = (over: Partial<ScriptExportParams>): ScriptExportParams => ({
    filename: 'data.csv', fileType: 'binary', delimiter: ',', columnMapping: [1, 2],
    setNames: ['A', 'B'], model: 'venn2', shapeColors: { A: '#FFF200', B: '#2E3192' },
    enrichmentMetric: 'neglog10fdr', n: 2, sourceKind: 'file', hasHeader: true,
    sheetIndex: 0, headers: ['id', 'A', 'B'], rawData: [['g1', '1', '0']], ...over,
  });

  it('no-header import: script does NOT skip the first row', () => {
    const py = generatePythonScript(base({ hasHeader: false }));
    expect(py).not.toContain('next(reader)  # skip header');
  });

  it('multi-sheet Excel: script reads the selected sheet index', () => {
    const py = generatePythonScript(base({ filename: 'x.xlsx', sheetIndex: 2 }));
    expect(py).toContain('sheet_name=2');
    const r = generateRScript(base({ filename: 'x.xlsx', sheetIndex: 2 }));
    expect(r).toContain('sheet = 3');   // R is 1-based
  });

  it('npm aggregated export preserves items containing commas', () => {
    const js = generateNpmScript(base({ fileType: 'aggregated', delimiter: ';' }));
    // must NOT re-join on a bare comma (which would split "Smith, John")
    expect(js).not.toContain("].map(s => s.trim()).filter(Boolean).join(',')");
  });

  it('paste source embeds data inline and never reads a file', () => {
    for (const gen of [generatePythonScript, generateRScript, generateNpmScript]) {
      const s = gen(base({ sourceKind: 'paste', rawData: [['g1', '1', '0']] }));
      expect(s).toContain('g1');
      expect(s.toLowerCase()).not.toMatch(/open\(file|readlines\(file|readfilesync/);
    }
  });

  it('no dead hex-lowercase regex applied to set names', () => {
    const py = generatePythonScript(base({ setNames: ['Sales #1', 'Ops'] }));
    expect(py).toContain('Sales #1');   // set name text untouched
  });

  it('gmt gene-set files embed inline instead of misparsing the file', () => {
    const py = generatePythonScript(base({
      filename: 'sets.gmt', fileType: 'aggregated', delimiter: ',',
      rawData: [['geneA', 'geneB']], headers: ['SetOne', 'SetTwo'],
    }));
    expect(py).toContain('geneA');
    expect(py).not.toContain('open(FILE');
  });
});
