import { APP_VERSION, APP_NAME } from '../version.ts';

export interface ScriptExportParams {
  filename: string;
  fileType: 'binary' | 'aggregated';
  delimiter?: string;
  columnMapping: number[];
  setNames: string[];
  model: string;
  shapeColors: Record<string, string>;
  enrichmentMetric: 'neglog10fdr' | 'foldEnrichment';
  n: number;
  /** Where the data came from. 'file'/'sample' → a real local file the script can re-open;
   *  'paste'/'url' → no local file, data must be embedded inline. */
  sourceKind: 'file' | 'sample' | 'paste' | 'url';
  /** Whether the source file's first row is a header (mirrors the import dialog checkbox). */
  hasHeader: boolean;
  /** 0-based worksheet index for .xlsx sources. */
  sheetIndex: number;
  /** Column headers (already resolved). */
  headers: string[];
  /** The parsed data rows (post-import), used for inline embedding of paste/url sources. */
  rawData: string[][];
}

const LETTERS = 'ABCDEFGHI';

export function toPythonColorMap(colors: Record<string, string>, n: number): string {
  const entries: string[] = [];
  for (let i = 0; i < n; i++) {
    const letter = LETTERS[i];
    const color = colors[letter] ?? '#666666';
    entries.push(`${JSON.stringify(letter)}: ${JSON.stringify(color)}`);
  }
  return `{${entries.join(', ')}}`;
}

export function toRColorVector(colors: Record<string, string>, n: number): string {
  const values: string[] = [];
  for (let i = 0; i < n; i++) {
    const letter = LETTERS[i];
    const color = colors[letter] ?? '#666666';
    values.push(`${letter} = ${JSON.stringify(color)}`);
  }
  return `c(${values.join(', ')})`;
}

function toPythonStringList(items: string[]): string {
  return `[${items.map(s => JSON.stringify(s)).join(', ')}]`;
}

function toPythonIntList(items: number[]): string {
  return `[${items.join(', ')}]`;
}

function quotePython(s: string): string {
  return JSON.stringify(s);
}

function quoteR(s: string): string {
  return JSON.stringify(s);
}

function inferFileDelimiter(filename: string): string {
  const lower = filename.toLowerCase();
  if (lower.endsWith('.tsv')) return '\\t';
  if (lower.endsWith('.csv')) return ',';
  if (lower.endsWith('.txt')) return ',';
  return ',';
}

function isExcelFilename(filename: string): boolean {
  return filename.toLowerCase().endsWith('.xlsx');
}

function isGeneSetFilename(filename: string): boolean {
  const lower = filename.toLowerCase();
  return lower.endsWith('.gmt') || lower.endsWith('.gmx');
}

/**
 * Decide whether the generated script must embed the parsed rows inline instead of
 * re-reading the on-disk file. Inline is required when the original file cannot be
 * reproduced by a simple CSV/Excel reader: paste/url sources have no local file, and
 * .gmt/.gmx gene-set files are transposed/tab-shaped and would misparse. `rawData` is
 * the app's already-parsed, header-stripped rows, so the inline branch never skips a header.
 */
function shouldEmbedInline(params: ScriptExportParams): boolean {
  return params.sourceKind === 'paste'
    || params.sourceKind === 'url'
    || isGeneSetFilename(params.filename);
}

/** Emit rows as an inline Python literal so paste/url/gmt data needs no file. */
function embedRowsPython(rows: string[][]): string {
  const body = rows.map(r => '    ' + toPythonStringList(r)).join(',\n');
  return `rows = [\n${body}\n]`;
}

/** Emit rows as an inline R literal (list of character vectors). */
function embedRowsR(rows: string[][]): string {
  const rowLits = rows.map(r => `c(${r.map(quoteR).join(', ')})`);
  return `rows <- list(\n    ${rowLits.join(',\n    ')}\n)`;
}

/** Emit rows as an inline JS literal (array of string arrays). */
function embedRowsJs(rows: string[][]): string {
  const body = rows.map(r => '  [' + r.map(quoteJs).join(', ') + ']').join(',\n');
  return `const rows = [\n${body}\n];`;
}

export function generatePythonScript(params: ScriptExportParams): string {
  const { filename, fileType, delimiter, columnMapping, setNames, model, shapeColors, enrichmentMetric, n } = params;
  const timestamp = new Date().toISOString();
  const effectiveModel = model === '__proportional__' ? 'proportional' : model;
  const letters = LETTERS.slice(0, n).split('');

  const lines: string[] = [
    `# Generated by ${APP_NAME} v${APP_VERSION} on ${timestamp}`,
    `# Source: ${filename}`,
    `# Model: ${effectiveModel}`,
    `# Columns (0-based): ${toPythonIntList(columnMapping)}`,
    `# Set names: ${toPythonStringList(setNames)}`,
    `# Enrichment metric: ${enrichmentMetric}`,
  ];

  if (model === '__proportional__') {
    lines.push('# Note: area-proportional mode (2-3 sets only)');
  }

  lines.push(
    '',
    'from venn_diagram_lab import Dataset, analyze, render_venn_svg, render_upset, render_network',
    '',
    `FILE = ${quotePython(filename)}`,
    `COLUMNS = ${toPythonIntList(columnMapping)}`,
    `SET_NAMES = ${toPythonStringList(setNames)}`,
    '',
  );

  if (shouldEmbedInline(params)) {
    lines.push(
      `# Data embedded inline (source: ${params.sourceKind}); already parsed and`,
      `# header-stripped by ${APP_NAME}, so no file is read here.`,
      embedRowsPython(params.rawData),
      '',
    );
  } else if (isExcelFilename(filename)) {
    lines.push(
      '# Excel file: install pandas and openpyxl (pip install pandas openpyxl)',
      'import pandas as pd',
      '',
      `df = pd.read_excel(FILE, sheet_name=${params.sheetIndex}, dtype=str, keep_default_na=False)`,
      'rows = df.values.tolist()',
      '',
    );
  } else {
    const fileDelimiter = inferFileDelimiter(filename);
    const isTsv = fileDelimiter === '\\t';
    const readerLines = [
      'import csv',
      '',
      `with open(FILE, newline="", encoding="utf-8") as f:`,
      `    reader = csv.reader(f, delimiter=${quotePython(isTsv ? '\t' : ',')})`,
    ];
    if (params.hasHeader) {
      readerLines.push('    _ = next(reader)  # skip header');
    }
    readerLines.push('    rows = list(reader)', '');
    lines.push(...readerLines);
  }

  if (fileType === 'binary') {
    lines.push(
      'items = {name: set() for name in SET_NAMES}',
      'item_order = []',
      'for row in rows:',
      '    if not row or not str(row[0]).strip():',
      '        continue',
      '    item_id = str(row[0]).strip()',
      '    item_order.append(item_id)',
      '    for col_idx, set_name in zip(COLUMNS, SET_NAMES):',
      '        val = (row[col_idx] if col_idx < len(row) else "").strip().lower()',
      '        if val in {"1", "true", "yes"}:',
      '            items[set_name].add(item_id)',
      '',
      'ds = Dataset.from_dict(',
      '    items,',
      `    source_path=FILE,`,
      `    format=${quotePython(filename.toLowerCase().endsWith('.tsv') ? 'tsv' : 'csv')},`,
      ')',
    );
  } else {
    const itemDelimiter = delimiter ?? ',';
    lines.push(
      `ITEM_DELIMITER = ${quotePython(itemDelimiter)}`,
      'items = {name: set() for name in SET_NAMES}',
      'item_order = []',
      'for row in rows:',
      '    for col_idx, set_name in zip(COLUMNS, SET_NAMES):',
      '        cell = (row[col_idx] if col_idx < len(row) else "").strip()',
      '        if not cell:',
      '            continue',
      '        for item in cell.split(ITEM_DELIMITER):',
      '            item = item.strip()',
      '            if item:',
      '                items[set_name].add(item)',
      '                if item not in item_order:',
      '                    item_order.append(item)',
      '',
      'ds = Dataset.from_dict(',
      '    items,',
      `    source_path=FILE,`,
      `    format=${quotePython(filename.toLowerCase().endsWith('.tsv') ? 'tsv' : 'csv')},`,
      ')',
    );
  }

  const setNamesMap = Object.fromEntries(letters.map((letter, i) => [letter, setNames[i] ?? letter]));
  const colorsMap = Object.fromEntries(letters.map(letter => [letter, shapeColors[letter] ?? '#666666']));

  lines.push(
    '',
    '# Analyze and render',
    `result = analyze(ds, model=${quotePython(effectiveModel)})`,
    '',
    '# Venn diagram (template or proportional)',
    'venn_svg = render_venn_svg(',
    '    result,',
    `    model=${quotePython(effectiveModel)},`,
    `    set_names=${toPythonColorMap(setNamesMap, n)},`,
    `    colors=${toPythonColorMap(colorsMap, n)},`,
    '    title="",',
    ')',
    'venn_svg.save("venn.svg")',
    '',
    '# UpSet plot',
    'render_upset(result, sort_by="size", max_columns=20, color_mode="heatmap").save("upset.png", dpi=300)',
    '',
    '# Network plot',
    'render_network(result, edge_metric="jaccard").save("network.png", dpi=300)',
    '',
    '# TSV exports',
    'result.to_region_summary_tsv("region_summary.tsv")',
    'result.to_matrix_tsv("item_matrix.tsv")',
    'result.to_statistics_tsv("statistics.tsv")',
  );

  return lines.join('\n');
}

export function generateRScript(params: ScriptExportParams): string {
  const { filename, fileType, delimiter, columnMapping, setNames, model, shapeColors, enrichmentMetric, n } = params;
  const timestamp = new Date().toISOString();
  const effectiveModel = model === '__proportional__' ? 'proportional' : model;
  const rColumns = columnMapping.map(i => i + 1);
  const letters = LETTERS.slice(0, n).split('');

  const lines: string[] = [
    `# Generated by ${APP_NAME} v${APP_VERSION} on ${timestamp}`,
    `# Source: ${filename}`,
    `# Model: ${effectiveModel}`,
    `# Columns (1-based): ${rColumns.join(', ')}`,
    `# Set names: ${setNames.map(quoteR).join(', ')}`,
    `# Enrichment metric: ${enrichmentMetric}`,
  ];

  if (model === '__proportional__') {
    lines.push('# Note: area-proportional mode (2-3 sets only)');
  }

  lines.push(
    '',
    'library(vennDiagramLab)',
    '',
    `FILE <- ${quoteR(filename)}`,
    `COLUMNS <- c(${rColumns.join(', ')})`,
    `SET_NAMES <- c(${setNames.map(quoteR).join(', ')})`,
    '',
  );

  if (shouldEmbedInline(params)) {
    lines.push(
      `# Data embedded inline (source: ${params.sourceKind}); already parsed and`,
      `# header-stripped by ${APP_NAME}, so no file is read here.`,
      embedRowsR(params.rawData),
      '',
    );
  } else if (isExcelFilename(filename)) {
    lines.push(
      '# Excel file: install openxlsx (install.packages("openxlsx"))',
      `df <- openxlsx::read.xlsx(FILE, sheet = ${params.sheetIndex + 1}, colNames = ${params.hasHeader ? 'TRUE' : 'FALSE'})`,
      'rows <- lapply(seq_len(nrow(df)), function(i) as.character(df[i, ]))',
      '',
    );
  } else {
    const isTsv = filename.toLowerCase().endsWith('.tsv');
    lines.push(
      '# Quote-aware line splitter (mirrors the app CSV parser: honors "..." and escaped "").',
      'split_csv_line <- function(line, delimiter) {',
      '    chars <- strsplit(line, "", fixed = TRUE)[[1]]',
      '    result <- character(0)',
      '    current <- ""',
      '    in_quotes <- FALSE',
      '    i <- 1L',
      '    n <- length(chars)',
      '    while (i <= n) {',
      '        ch <- chars[i]',
      '        if (ch == "\\"") {',
      '            if (in_quotes && i < n && chars[i + 1L] == "\\"") {',
      '                current <- paste0(current, "\\"")',
      '                i <- i + 1L',
      '            } else {',
      '                in_quotes <- !in_quotes',
      '            }',
      '        } else if (ch == delimiter && !in_quotes) {',
      '            result <- c(result, trimws(current))',
      '            current <- ""',
      '        } else {',
      '            current <- paste0(current, ch)',
      '        }',
      '        i <- i + 1L',
      '    }',
      '    c(result, trimws(current))',
      '}',
      '',
      `DELIMITER <- ${quoteR(isTsv ? '\t' : ',')}`,
      `raw <- readLines(FILE, warn = FALSE, encoding = "UTF-8")`,
      `lines <- raw[nzchar(trimws(raw))]`,
      `parsed <- lapply(lines, split_csv_line, delimiter = DELIMITER)`,
      params.hasHeader ? 'rows <- parsed[-1]' : 'rows <- parsed',
      '',
    );
  }

  if (fileType === 'binary') {
    lines.push(
      'items <- setNames(replicate(length(SET_NAMES), character(0), simplify = FALSE), SET_NAMES)',
      'item_order <- character()',
      'for (row in rows) {',
      '    if (length(row) == 0L || !nzchar(trimws(row[1]))) next',
      '    item_id <- trimws(row[1])',
      '    item_order <- c(item_order, item_id)',
      '    for (i in seq_along(COLUMNS)) {',
      '        col_idx <- COLUMNS[i]',
      '        set_name <- SET_NAMES[i]',
      '        val <- if (col_idx <= length(row)) trimws(row[col_idx]) else ""',
      '        if (tolower(val) %in% c("1", "true", "yes")) {',
      '            items[[set_name]] <- c(items[[set_name]], item_id)',
      '        }',
      '    }',
      '}',
      'items <- lapply(items, unique)',
      'item_order <- unique(item_order)',
      '',
      'ds <- methods::new("VennDataset",',
      '    set_names     = SET_NAMES,',
      '    items         = items,',
      '    item_order    = item_order,',
      '    universe_size = length(item_order),',
      '    source_path   = FILE,',
      `    format        = ${quoteR(filename.toLowerCase().endsWith('.tsv') ? 'tsv' : 'csv')}`,
      ')',
    );
  } else {
    const itemDelimiter = delimiter ?? ',';
    lines.push(
      `ITEM_DELIMITER <- ${quoteR(itemDelimiter)}`,
      'items <- setNames(replicate(length(SET_NAMES), character(0), simplify = FALSE), SET_NAMES)',
      'item_order <- character()',
      'for (row in rows) {',
      '    for (i in seq_along(COLUMNS)) {',
      '        col_idx <- COLUMNS[i]',
      '        set_name <- SET_NAMES[i]',
      '        cell <- if (col_idx <= length(row)) trimws(row[col_idx]) else ""',
      '        if (!nzchar(cell)) next',
      '        parts <- trimws(strsplit(cell, ITEM_DELIMITER, fixed = TRUE)[[1]])',
      '        parts <- parts[nzchar(parts)]',
      '        items[[set_name]] <- c(items[[set_name]], parts)',
      '        for (item in parts) {',
      '            if (!item %in% item_order) item_order <- c(item_order, item)',
      '        }',
      '    }',
      '}',
      'items <- lapply(items, unique)',
      '',
      'ds <- methods::new("VennDataset",',
      '    set_names     = SET_NAMES,',
      '    items         = items,',
      '    item_order    = item_order,',
      '    universe_size = NULL,',
      '    source_path   = FILE,',
      `    format        = ${quoteR(filename.toLowerCase().endsWith('.tsv') ? 'tsv' : 'csv')}`,
      ')',
    );
  }

  const setNamesVector = letters.map((letter, i) => `${letter} = ${quoteR(setNames[i] ?? letter)}`).join(', ');
  const colorsVector = letters.map(letter => `${letter} = ${quoteR(shapeColors[letter] ?? '#666666')}`).join(', ');

  lines.push(
    '',
    '# Analyze and render',
    `result <- analyze(ds, model = ${quoteR(effectiveModel)})`,
    '',
    '# Venn diagram (template or proportional)',
    `svg <- render_venn_svg(result, model = ${quoteR(effectiveModel)}, set_names = c(${setNamesVector}), colors = c(${colorsVector}), title = "")`,
    'writeLines(svg, "venn.svg")',
    '',
    '# UpSet plot',
    'ggsave("upset.png", render_upset(result, sort_by = "size", max_columns = 20L, color_mode = "heatmap"), width = 8, height = 5)',
    '',
    '# Network plot',
    'ggsave("network.png", render_network(result, edge_metric = "jaccard"), width = 7, height = 6)',
    '',
    '# TSV exports',
    'to_region_summary_tsv(result, "region_summary.tsv")',
    'to_matrix_tsv(result, "item_matrix.tsv")',
    'to_statistics_tsv(result, "statistics.tsv")',
  );

  return lines.join('\n');
}

function quoteJs(s: string): string {
  return JSON.stringify(s);
}

function toJsArray(items: (string | number)[]): string {
  return `[${items.map(s => typeof s === 'number' ? String(s) : quoteJs(s)).join(', ')}]`;
}

function toJsColorMap(colors: Record<string, string>, n: number): string {
  const entries: string[] = [];
  for (let i = 0; i < n; i++) {
    const letter = LETTERS[i];
    const color = colors[letter] ?? '#666666';
    entries.push(`${quoteJs(letter)}: ${quoteJs(color)}`);
  }
  return `{${entries.join(', ')}}`;
}

export function generateNpmScript(params: ScriptExportParams): string {
  const { filename, fileType, delimiter, columnMapping, setNames, model, shapeColors, enrichmentMetric, n } = params;
  const timestamp = new Date().toISOString();
  const effectiveModel = model === '__proportional__' ? 'proportional' : model;
  const fileDelimiter = inferFileDelimiter(filename);
  const isTsv = fileDelimiter === '\\t';
  const inline = shouldEmbedInline(params);

  const lines: string[] = [
    `// Generated by ${APP_NAME} v${APP_VERSION} on ${timestamp}`,
    `// Source: ${filename}`,
    `// Model: ${effectiveModel}`,
    `// Columns (0-based): ${toJsArray(columnMapping)}`,
    `// Set names: ${toJsArray(setNames)}`,
    `// Colors: ${toJsColorMap(shapeColors, n)}`,
    `// Enrichment metric: ${enrichmentMetric}`,
    `// File type: ${fileType}`,
  ];

  if (model === '__proportional__') {
    lines.push('// Note: area-proportional mode (2-3 sets only)');
  }

  lines.push(
    '',
    `import { ${inline ? '' : 'readFileSync, '}writeFileSync } from 'node:fs';`,
    'import {',
    '  analyzeCsv,',
    '  toVennSvg,',
    '  toUpsetSvg,',
    '  toNetworkSvg,',
    '  toStatisticsTsv,',
    '  toMatrixTsv,',
    '  toRegionSummaryTsv,',
    '  toProportionalSvg,',
    '} from \'venn-diagram-lab\';',
    '',
    `const COLUMNS = ${toJsArray(columnMapping)};`,
    `const MODEL = ${quoteJs(effectiveModel)};`,
    '',
  );

  if (inline) {
    lines.push(
      `// Data embedded inline (source: ${params.sourceKind}); already parsed and`,
      `// header-stripped by ${APP_NAME}, so no file is read here.`,
      embedRowsJs(params.rawData),
      `const headers = ${toJsArray(params.headers)};`,
      '',
    );
  } else {
    lines.push(`const FILE = ${quoteJs(filename)};`, '');
    if (isExcelFilename(filename)) {
      lines.push(
        `// Excel file: convert to CSV first (using worksheet index ${params.sheetIndex}, 0-based), e.g. with the xlsx package:`,
        '//   import xlsx from \'xlsx\';',
        '//   const workbook = xlsx.readFile(FILE);',
        `//   const worksheet = workbook.Sheets[workbook.SheetNames[${params.sheetIndex}]];`,
        '//   const csv = xlsx.utils.sheet_to_csv(worksheet);',
        '//   writeFileSync(\'converted.csv\', csv);',
        '// Then update FILE to point to the converted CSV file.',
        '',
      );
    }
    lines.push(
      `const FILE_DELIMITER = ${quoteJs(isTsv ? '\t' : ',')};`,
      '',
      '// Quote-aware line splitter (mirrors the app CSV parser: honors "..." and escaped "").',
      'function splitCsvLine(line, delimiter) {',
      '  const result = [];',
      '  let current = \'\';',
      '  let inQuotes = false;',
      '  for (let i = 0; i < line.length; i++) {',
      '    const ch = line[i];',
      '    if (ch === \'"\') {',
      '      if (inQuotes && line[i + 1] === \'"\') { current += \'"\'; i++; }',
      '      else { inQuotes = !inQuotes; }',
      '    } else if (ch === delimiter && !inQuotes) {',
      '      result.push(current.trim());',
      '      current = \'\';',
      '    } else {',
      '      current += ch;',
      '    }',
      '  }',
      '  result.push(current.trim());',
      '  return result;',
      '}',
      '',
      'function parseCsvFile(path, delimiter) {',
      '  const text = readFileSync(path, \'utf-8\');',
      '  const lines = text.replace(/\\r\\n/g, \'\\n\').replace(/\\r/g, \'\\n\').trim().split(\'\\n\').filter(l => l.trim() !== \'\');',
      `  const dataStart = ${params.hasHeader ? '1' : '0'};`,
      `  const headers = ${params.hasHeader ? 'splitCsvLine(lines[0], delimiter)' : `${toJsArray(params.headers)}`};`,
      '  const rows = lines.slice(dataStart).map(line => splitCsvLine(line, delimiter));',
      '  return { headers, rows };',
      '}',
      '',
      'const { headers, rows } = parseCsvFile(FILE, FILE_DELIMITER);',
      '',
    );
  }

  if (fileType === 'binary') {
    lines.push(
      '// Binary mode: first column is treated as the item identifier, selected columns are the binary set memberships.',
      'const csv = {',
      '  headers: [headers[0], ...COLUMNS.map(i => headers[i] ?? `Column ${i + 1}`)],',
      '  rows: rows.map(row => [row[0], ...COLUMNS.map(i => row[i] ?? \'\')]),',
      '};',
    );
  } else {
    const itemDelimiter = delimiter ?? ',';
    lines.push(
      `const ITEM_DELIMITER = ${quoteJs(itemDelimiter)};`,
      '',
      '// Aggregated mode: each selected column is a set, cells contain delimiter-separated items.',
      '// NOTE (package limitation): the published `venn-diagram-lab` `analyzeCsv` splits aggregated',
      '// cells on a hardcoded comma and exposes no delimiter override. When ITEM_DELIMITER is not a',
      '// comma we re-split on the true delimiter and re-join with a comma. That is lossless ONLY if',
      '// no item itself contains a comma; the guard below throws rather than silently splitting an',
      '// item such as "Smith, John" into two. (Comma-in-item aggregated data cannot round-trip',
      '// through the npm package — export a comma-delimited file, or use the Python/R script.)',
      'const csv = {',
      '  headers: COLUMNS.map(i => headers[i] ?? `Column ${i + 1}`),',
      '  rows: rows.map(row => COLUMNS.map(i => {',
      '    const cell = row[i] ?? \'\';',
      '    if (ITEM_DELIMITER === \',\') return cell;',
      '    const parts = cell.split(ITEM_DELIMITER).map(s => s.trim()).filter(Boolean);',
      '    if (parts.some(p => p.includes(\',\'))) {',
      '      throw new Error(\'An aggregated item contains a comma; venn-diagram-lab splits cells on commas and cannot represent it losslessly.\');',
      '    }',
      '    return parts.join(\',\');',
      '  })),',
      '};',
    );
  }

  lines.push(
    '',
    '// Analyze and render',
    'const result = analyzeCsv(csv);',
    '',
    '// Venn diagram (template or area-proportional)',
    'const vennSvg = MODEL === \'proportional\' ? toProportionalSvg(result) : toVennSvg(result, MODEL);',
    'writeFileSync(\'venn_diagram.svg\', vennSvg);',
    '',
    '// UpSet plot',
    'writeFileSync(\'upset_plot.svg\', toUpsetSvg(result));',
    '',
    '// Network plot',
    'writeFileSync(\'network.svg\', toNetworkSvg(result, \'jaccard\'));',
    '',
    '// TSV exports',
    'writeFileSync(\'region_summary.tsv\', toRegionSummaryTsv(result));',
    'writeFileSync(\'item_matrix.tsv\', toMatrixTsv(result));',
    'writeFileSync(\'statistics.tsv\', toStatisticsTsv(result));',
  );

  return lines.join('\n');
}
