"""Byte-for-byte parity of the network exporters vs the webapp goldens.

For each (sample, model) pair, analyze the bundled sample with the model
baked into the golden filename and assert `to_network_graphml_str()` /
`to_network_sif_str()` equal the committed `*__network.{graphml,sif}`
fixtures byte-for-byte.

Fixtures are generated by the TypeScript source of truth
(``scripts/generate-parity-fixtures.mts``); see ``test_parity_with_webapp.py``
and ``.superpowers/sdd/task-F8-ts-report.md``.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from venn_diagram_lab.analysis import analyze
from venn_diagram_lab.samples import load_sample

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "expected"

# (sample_name, model_name) — must match scripts/generate-parity-fixtures.mts
# and test_parity_json.py.
PAIRS: list[tuple[str, str]] = [
    ("dataset_real_cancer_drivers_4",       "venn-4-set"),
    ("dataset_real_msigdb_immune_pathways", "venn-4-set"),
    ("dataset_real_msigdb_cancer_pathways", "venn-5-set-grunbaum"),
    ("dataset_mock_gene_sets",              "venn-6-set"),
    ("dataset_mock_streaming_platforms",    "venn-8-set"),
]

# Same divergence documented in test_parity_json.py / test_parity_with_webapp.py:
# the webapp's row-based binary loader treats duplicate titles as distinct
# items, while the Python set-based loader deduplicates. Strict xfail so a
# future reconciliation forces the marker's removal.
_DUPLICATE_TITLE_SAMPLES = frozenset({"dataset_mock_streaming_platforms"})


@pytest.mark.parametrize(("sample_name", "model"), PAIRS, ids=[p[0] for p in PAIRS])
def test_graphml_matches_webapp_bytes(sample_name: str, model: str) -> None:
    """Strict byte-for-byte comparison against the committed GraphML golden."""
    fixture = FIXTURES_DIR / f"{sample_name}__{model}__network.graphml"
    assert fixture.is_file(), f"Missing fixture: {fixture} (run: npm run fixtures:parity)"

    result = analyze(load_sample(sample_name), model="auto")
    actual = result.to_network_graphml_str()

    if sample_name in _DUPLICATE_TITLE_SAMPLES:
        pytest.xfail(
            "Webapp's row-based binary loader vs Python's set-based loader "
            "diverge on duplicate identifiers (e.g. two 'Dark Matter' titles). "
            "See test_parity_with_webapp.py module docstring."
        )

    expected = fixture.read_text(encoding="utf-8")
    assert actual == expected, (
        f"GraphML byte mismatch for {sample_name}/{model} "
        f"(actual {len(actual)} chars vs expected {len(expected)} chars)"
    )


@pytest.mark.parametrize(("sample_name", "model"), PAIRS, ids=[p[0] for p in PAIRS])
def test_sif_matches_webapp_bytes(sample_name: str, model: str) -> None:
    """Strict byte-for-byte comparison against the committed SIF golden."""
    fixture = FIXTURES_DIR / f"{sample_name}__{model}__network.sif"
    assert fixture.is_file(), f"Missing fixture: {fixture} (run: npm run fixtures:parity)"

    result = analyze(load_sample(sample_name), model="auto")
    actual = result.to_network_sif_str()

    if sample_name in _DUPLICATE_TITLE_SAMPLES:
        pytest.xfail(
            "Webapp's row-based binary loader vs Python's set-based loader "
            "diverge on duplicate identifiers (e.g. two 'Dark Matter' titles). "
            "See test_parity_with_webapp.py module docstring."
        )

    expected = fixture.read_text(encoding="utf-8")
    assert actual == expected, (
        f"SIF byte mismatch for {sample_name}/{model} "
        f"(actual {len(actual)} chars vs expected {len(expected)} chars)"
    )
